###
GET http://localhost:8000/users

###
DELETE http://localhost:8000/users/2

###
POST http://localhost:8000/users 
Content-Type: application/json

{ "id": "5", "name": "Gonzalo", "lastname": "Garcia", "user": "Barba Nuevo", "email": "barbanuevo@gmail.com" }

###
PUT http://localhost:8000/users/3 
Content-Type: application/json

{ "id": "3", "name": "Mini", "lastname": "Justo", "user": "MJ", "email": "mj@gmail.com" }

###
GET http://localhost:8000/users